CREATE TABLE `clubinvoice`.`ADRESS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ADRESS_TYPE` VARCHAR(31) NOT NULL,
  `ADRESS1` VARCHAR(255) NULL,
  `ADRESS2` VARCHAR(255) NULL,
  `ZIP` VARCHAR(45) NULL,
  `CITY` VARCHAR(155) NULL,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
