CREATE TABLE `clubinvoice`.`banking_connection`(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    OWNER_TYPE VARCHAR(31) NOT NULL,
    BANKNAME VARCHAR(255),
    BIC VARCHAR(255),
    IBAN VARCHAR(255),
  	UNIQUE INDEX `banking_connection_UNIQUE` (`ID`, `OWNER_TYPE`, `IBAN` ASC)
);